### ISSUE TITLE
config.yml removed once sing off

### ISSUE THREAD

**Issue by ifridemberg** [devshawn/kafka-shell#12]
the config.yml files are removed once signoff of remote server.

best regards.

Ignacio F

**Comment by devshawn** [comment]
Hi, thanks for reporting this issue.

Are you losing your home directory when you log out? By default, config is stored at `~/.kafka-shell`. If your home directory is lost on sign out, you'll lose your config. I'll try this out tonight when I get some free time.

**Comment by devshawn** [comment]
Hi @ifridemberg,

Are you still seeing this issue?
