### ISSUE TITLE
cannot launch kafka-shell

### ISSUE THREAD

**Issue by PGDataHome** [devshawn/kafka-shell#16]
**Describe the bug**

here's my output
hadoop@pascal-asus:~/kafka$ kafka-shell
Invalid user configuration (root): None is not of type 'object'
hadoop@pascal-asus:~/kafka$ 

**To Reproduce**
1. Run `kafka-shell`
2. ...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [i.e. macOS Mojave]
 - Version [e.g. 0.1.0]

**Additional context**

**Comment by devshawn** [comment]
Hi @PGDataHome, can you share your contents of the `config.yaml` file?

`cat ~/.kafka-shell/config.yaml`

If you haven't modified the config, you should be able to delete it and re-launch `kafka-shell` and it will generate a new one.

**Comment by PGDataHome** [comment]
cat ~/.kafka-shell/config.yaml
-- file is empty

Le sam. 23 nov. 2019 à 18:43, Shawn Seymour <notifications@github.com> a
écrit :

**Comment by PGDataHome** [comment]
here's complete transcript, included  my trial, and trace error

----------------------
hadoop@pascal-asus:~/kafka$ cat ~/.kafka-shell/config.yaml
hadoop@pascal-asus:~/kafka$ rm ~/.kafka-shell/config.yaml
hadoop@pascal-asus:~/kafka$ cd kafka-shell
bash: cd: kafka-shell: No such file or directory
hadoop@pascal-asus:~/kafka$ which kafka-shell
/usr/local/bin/kafka-shell
hadoop@pascal-asus:~/kafka$ kafka-shell
Traceback (most recent call last):
  File "/usr/local/bin/kafka-shell", line 11, in <module>
    load_entry_point('kafka-shell==0.1.2', 'console_scripts',
'kafka-shell')()
  File
"/usr/local/lib/python3.7/dist-packages/kafka_shell-0.1.2-py3.7.egg/kafkashell/main.py",
line 32, in main
    settings = Settings()
  File
"/usr/local/lib/python3.7/dist-packages/kafka_shell-0.1.2-py3.7.egg/kafkashell/settings.py",
line 27, in __init__
    config.init_config()
  File
"/usr/local/lib/python3.7/dist-packages/kafka_shell-0.1.2-py3.7.egg/kafkashell/config.py",
line 45, in init_config
    save_yaml(default_config, f)
  File
"/usr/local/lib/python3.7/dist-packages/kafka_shell-0.1.2-py3.7.egg/kafkashell/config.py",
line 97, in save_yaml
    yaml.dump(config, f, default_flow_style=False, sort_keys=False)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
hadoop@pascal-asus:~/kafka$

Le dim. 24 nov. 2019 à 10:26, Pascal GUICHARD <pascal.guichard@gmail.com> a
écrit :

**Comment by devshawn** [comment]
Hi @PGDataHome, thanks for the very helpful stacktrace. I believe this is happening due to an outdated `pyyaml` version on your machine. That package is not currently pinned to a newer version in `kafka-shell` as I'm using a wrapper library that includes it. I'll update the repo to pin the module, but you should be able to fix this by running:

`rm ~/.kafka-shell/config.yaml && pip3 install 'pyyaml==5.1'` 

Then, you can run `kafka-shell`. I hope that helps!

**Comment by PGDataHome** [comment]
ok, I can launch kafka-shell
rhx

Le dim. 24 nov. 2019 à 16:30, Shawn Seymour <notifications@github.com> a
écrit :

**Comment by devshawn** [comment]
Happy to hear!
